### PR TITLE
An experiment, adding support for promises.

### PR DESCRIPTION
**Pull request by jmdobry**
Usage:

**`Speech#recognize`**:

```js
// Callback-style
speech.recognize('./audio.raw', { sampleRate: 16000 }, function (err, results, apiResponse) {
  if (err) {
    console.log(err.message); // "Some error message..."
    console.log(err.apiResponse); // {...}
    console.log(results); // undefined
    console.log(apiResponse); // undefined
  } else {
    console.log(err); // null
    console.log(results); // "The bridge goes to the other side."
    console.log(apiResponse); // {...}
  }
});

// Promise + destructuring
speech.recognize('./audio.raw', { sampleRate: 16000 })
  .then(function ([results, apiResponse]) {
    console.log(err); // null
    console.log(results); // "The bridge goes to the other side."
    console.log(apiResponse); // {...}
  })
  .catch(function (err) {
    console.log(err.message); // "Some error message..."
    console.log(err.apiResponse); // {...}
  });

// Promise + .spread() (Bluebird.js)
speech.recognize('./audio.raw', { sampleRate: 16000 })
  .spread(function (results, apiResponse) {
    console.log(err); // null
    console.log(results); // "The bridge goes to the other side."
    console.log(apiResponse); // {...}
  })
  .catch(function (err) {
    console.log(err.message); // "Some error message..."
    console.log(err.apiResponse); // {...}
  });
```

**`Speech#startRecognition`** (long-running-operation):

```js
// Callback-style
speech.startRecognition('./audio.raw', { sampleRate: 16000 }, function (err, operation, apiResponse) {
  if (err) {
    console.log(err.message); // "Some error message..."
    console.log(err.apiResponse); // {...}
    console.log(operation); // undefined
    console.log(apiResponse); // undefined
  } else {
    console.log(err); // null
    console.log(operation); // {...}
    console.log(apiResponse); // {...}

    operation
      .on('complete', function (results, apiResponse) {
        console.log(results); // "The bridge goes to the other side."
        console.log(apiResponse); // {...}
      })
      .on('error', function (err) {
        console.log(err.message); // "Some error message..."
      });
  }
});

// Promise + destructuring
speech.startRecognition('./audio.raw', { sampleRate: 16000 })
  .then(function ([operation, apiResponse]) {
    console.log(err); // null
    console.log(operation); // {...}
    console.log(apiResponse); // {...}

    operation
      .on('complete', function (results, apiResponse) {
        console.log(results); // "The bridge goes to the other side."
        console.log(apiResponse); // {...}
      })
      .on('error', function (err) {
        console.log(err.message); // "Some error message..."
      });
  })
  .catch(function (err) {
    console.log(err.message); // "Some error message..."
    console.log(err.apiResponse); // {...}
  });

// Promise + .spread() (Bluebird.js)
speech.startRecognition('./audio.raw', { sampleRate: 16000 })
  .spread(function (operation, apiResponse) {
    console.log(err); // null
    console.log(operation); // {...}
    console.log(apiResponse); // {...}

    operation
      .on('complete', function (results, apiResponse) {
        console.log(results); // "The bridge goes to the other side."
        console.log(apiResponse); // {...}
      })
      .on('error', function (err) {
        console.log(err.message); // "Some error message..."
      });
  })
  .catch(function (err) {
    console.log(err.message); // "Some error message..."
    console.log(err.apiResponse); // {...}
  });
```

**`Speech#createRecognizeStream`**:

```js
// There's only one style with streams
var stream = speech.recognize('./audio.raw', { sampleRate: 16000 });

stream
  .on('data', function (...) {
    // ...
  })
  .on('error', function (...) {
    // ...
  });
```

### CODE REVIEW

**Comment by jmdobry** [comment]
@callmehiphop @jmuk If/when we add support for promises, this PR is how envision how it would work.

**Comment by jmdobry** [comment]
I was a little unsure about passing multiple values to `.reject`, which would necessitate the use of destructuring in `.catch()`. I think the various methods are inconsistent on they pass `err` + `apiResponse` to the callback. In my PR I attach `apiResponse` to `err` and just pass `err` to `.reject`. I think this would be weird:

```js
.catch(function ([err, , apiResponse]) {
  // ...
});
```

**Comment by callmehiphop** [comment]
Nice, thanks for putting this together! Your usage patterns look great, I think it's pretty close to how we were originally designing the API.

>  I think the various methods are inconsistent on how they pass err + apiResponse to the callback.

Yeah, that's probably true. I like the example where you create an `apiResponse` property on the Error object itself. I agree that destructuring in the failure path seems a bit off.

**Comment by jmdobry** [comment]
So use destructuring or `.spread()` to get the multiple values in the success path, while the failure path receives a single `err` value which possibly has additional stuff attached to it.

With that, async/await looks like this:

```js
async function runExample () {
  try {
    const [operation, apiResponse] = await speech.startRecognition('./audio.raw', { sampleRate: 16000 });

    operation
      .on('complete', function (results, apiResponse) {
        // ...
      })
      .on('error', function (err) {
        // ...
      });
  } catch (err) {
    console.log(err.message); // "Some error message..."
    console.log(err.apiResponse); // {...}
  }
}
```

**Comment by jmdobry** [comment]
@callmehiphop After looking through the implementation of `gax-nodejs`, I'm no longer convinced that we'd want to return Promises directly from method calls. The autogen layer returns an event emitter, which gives the user access to several cool features. One is observing the state of the operation, the second is the ability to cancel the request. In addition, `gax-nodejs` already uses promises under the hood, and can access the promise for the request at `EventEmitter#result`. Using the Language API as an example:

```js
var language = require('@google-cloud/language').v1beta1();

var document = {
  type: 'PLAIN_TEXT',
  content: 'Hello, world!'
};

// Callback-style
var eventEmitter = language.analyzeSentiment(document, (err, response) => {
  // ...
});

// if necessary for some reason
eventEmitter.cancel();
```

```js
// Promise-style
var eventEmitter = language.analyzeSentiment(document);

// if necessary for some reason
eventEmitter.cancel();

// This works today
eventEmitter.result
  .then((response) => {
    // ...
  })
  .catch((err) => {
    // ...
  });
```

If we return a promise directly from the method call, we lose out on the event emitter.

Perhaps one could argue for making the event emitter Promise-compatible.

**Comment by callmehiphop** [comment]
> Perhaps one could argue for making the event emitter Promise-compatible.

I think this is something we might want to look into, the EventEmitter obviously has a lot of value for our users, but I think that in most cases the user won't need such a finite level of control.

What are your feelings on usage similar to the following (assuming it's technically feasible).

```js
// promise style - most common use case
bigquery.getJobs().then(([jobs, apiResponse]) => {});

// event emitter - advanced use case
var ee = bigquery.getJobs();

ee.then(([jobs, apiResponse]) => {});
ee.cancel();
```

I feel like it's pretty similar to the above, the only difference being that with this approach users who don't care about the EventEmitter don't have to concern themselves with it.

**Comment by jmdobry** [comment]
Yeah, I'm not sure how I feel about mixing the two interfaces. Promises might get their own cancel semantics, which might be different than the cancel behavior provided by the event emitter.

**Comment by callmehiphop** [comment]
That's a good point. Maybe we should make the EventEmitter a vtk feature and return Promises in the hand written layer?

/cc @stephenplusplus

**Comment by jmdobry** [comment]
I'm thinking the hand-written layer just return the same event emitter that's
returned by the autogen layer, and let users access the promise at
`request.result`:

```js
var Language = require('@google-cloud/language');

var language = Language();
var api = Language.v1beta1();

var languageRequest = language.detectSentiment('Hello, world!');
var apiRequest = api.analyzeSentiment({
  type: 'PLAIN_TEXT',
  content: 'Hello, world!'
});

// if necessary for some reason
languageRequest.cancel();
apiRequest.cancel();

// This works today
languageRequest.result
  .then((sentiment) => {
    // ...
  })
  .catch((err) => {
    // ...
  });

apiRequest.result
  .then((response) => {
    // ...
  })
  .catch((err) => {
    // ...
  });
```

**Comment by stephenplusplus** [comment]
Instead of the handwritten API calls returning an event emitter and then a promise if asked for via a `result` property, can it return the promise directly, and the event emitter via a `request` property?

```js
var Language = require('@google-cloud/language');

var language = Language();
var api = Language.v1beta1();

var languageRequest = language.detectSentiment('Hello, world!')
  .then((sentiment) => {
    // ...
  })
  .catch((err) => {
    // ...
  });

languageRequest.request.cancel();
```

**Comment by callmehiphop** [comment]
@stephenplusplus for a variety of reasons I don't think that's wise. But I think the most obvious would be that each `then()` call returns a `new Promise`, meaning any custom assigned properties would be lost if the user were chaining like in your example. It would have to look more like

```js
var languageRequest = language.detectSentiment('Hello, world!');

languageRequest
  .then((sentiment) => {
    // ...
  })
  .catch((err) => {
    // ...
  });

languageRequest.request.cancel();
```

**Comment by stephenplusplus** [comment]
Isn't our example the same code?

**Comment by stephenplusplus** [comment]
I don't actually think your example code is that bad. Is that the only negative? Remember that we want to support *promises*, not cancel-ability (unless that comes from the promise API we return itself).

**Comment by callmehiphop** [comment]
We could, my biggest fear is that a number of issues would be opened due to user error. Our code snippets look identical, so unless someone really understands how Promises work, they might make the mistake of not accessing the right object.

**Comment by stephenplusplus** [comment]
I don't think users are super-into canceling their requests, so that would affect a subset of a subset. I'd rather cater the API to the majority.

**Comment by callmehiphop** [comment]
I definitely agree with your thinking there. @jmdobry thoughts?

**Comment by jmdobry** [comment]
When adding promises to google-cloud-node was first brought up, the idea was that google-cloud-node would accept a callback, or return a promise if no callback was provided. The only difference between the two is the style of control-flow.

`gax-nodejs` brings some new functionality to the table. The event emitter provides not just cancelability, but visibility into the state of the request via `.on`. So regardless of which control-flow style the developer prefers—callback or promise—they need to be able to access the request event emitter returned by `gax-nodejs` API calls.

Returning the promise directly with the event emitter attached will lead to a number of "bug" reports, as the absolute most common way to consume a promise is directly from the method call:

```js
language.detectSentiment('Hello, world!').then((sentiment) => {
  // ...
});
```

but with that you lose access to the event emitter.

I'm not a fan of inverting (or changing in general) what is returned by the autogen layer (both return values and what is passed to callbacks). Going forward, a lot of APIs won't need much hand-written stuff at all, and creating inconsistent experiences across APIs doesn't sound appealing to me. If we want to change something, we should change it in the autogen layer.

**Comment by stephenplusplus** [comment]
> they need to be able to access the request event emitter returned by gax-nodejs API calls.

I'm okay with them not having this through the handwritten layer. We're about making things super-simple, intuitive, and straightforward. No doubt that's a nice feature, but I'm okay with advising they go through the autogen layer if they need it.

> Returning the promise directly with the event emitter attached will lead to a number of "bug" reports

Agree. We shouldn't go that route.

> Going forward, a lot of APIs won't need much hand-written stuff at all, and creating inconsistent experiences across APIs doesn't sound appealing to me. If we want to change something, we should change it in the autogen layer.

This sounds like we're bouncing back to the much more confusing place of "Why is there a `google-cloud-node` at all?"-- which is actually quite a common question. I think we're here exactly because of discussions like this. We're trying to help the user get to the most common place as quickly as possible, instead of blasting options at them like a graphing calculator when all they need is simple arithmetic.

Of course, not my call to make, just my opinions. Happy to proceed in the direction that makes everyone happy.

**Comment by stephenplusplus** [comment]
// @omaray @jgeewax

**Comment by jmdobry** [comment]
Most APIs aren't a graphing calculator, they're just CRUD. Datastore is absolutely one of those APIs that needs a nice handwritten layer. Speech...I'm not so sure anymore. Right now, the handwritten Speech layer does the following:

- Renames methods
- Simplifies required input, even allows you to just pass a filename
- Squashes responses
- Possibly hide the request event emitter

The part that I find valuable is the second point, where it makes it easier to make the API call (I don't have to read a file from disc myself). In fact, I would argue that we should move that `_findFiles` helper function into `gax-nodejs` so that all APIs can benefit.

**Comment by stephenplusplus** [comment]
In terms of the graphing calculator, I meant our client APIs. It's great to have many options (ourselves, we have things like `autoPaginate`, `maxApiCalls`, `maxRetries`, request interceptors, etc), the only times they feel intrusive is when they're in the way of the most common requirement. I think we all agree the user expects our API to look like this;

```js
bucket.getFiles().then(...);
```

So, simply put, I don't think we should settle for anything else.

**Comment by jmdobry** [comment]
If returning a promise directly is the best user experience, then why are we settling for less in `gax-nodejs`?

**Comment by stephenplusplus** [comment]
I haven't been a part of that project's goals or development, so I don't want to speak on any specifics. But from my naive experience with it so far, it's "place" amongst our other libraries seems to be the "graphing calculator" for users who need advanced control, and don't want to wait for us to get around to implementing their required APIs. I expect it to be a bit robotic, and that's a feature. But of course, it should have high standards as well to be as UX-friendly as possible. In this case, it seems like it's doing a fine job of returning an event emitter and a promise separately, so I'm not sure I would say that needs to be changed.

**Pull request closed without merging**
